version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: